### ISSUE TITLE
assente

### ISSUE THREAD

**Issue by camillasaba** [sdoro/4E#10]
camillasaba - 4E-15

**Comment by cnllrnz** [comment]
cnllrnz - 4E-4

**Comment by ImNotGiaco** [comment]
bello

**Comment by sdoro** [comment]
grazie

**Comment by messus** [comment]
ciao

**Comment by zanealvi** [comment]
ciao

**Comment by Damimanda** [comment]
ciao

**Comment by Gegerva01** [comment]
SEGRETERIA!!

**Comment by Damimanda** [comment]
Gnocca di testa!!!!!!!!!1

**Comment by cnllrnz** [comment]
hey there i'm using whatsapp

**Comment by Byrykhynho** [comment]
uella belli... sta nutria putroccola

**Comment by barodani** [comment]
Stato: Italia

**Comment by Gegerva01** [comment]
Stato : Veneto

**Comment by Byrykhynho** [comment]
gerva simpi :)

**Comment by Gegerva01** [comment]
Ma non quanto il sistema nervoso

**Comment by Damimanda** [comment]
Kissy <3

**Comment by zanealvi** [comment]
shut up!!!!!!!

**Comment by Byrykhynho** [comment]
> Ma non quanto il sistema nervoso

xD

**Comment by Byrykhynho** [comment]
evviva haveloc

**Comment by zanealvi** [comment]
evloig*

**Comment by lunamale** [comment]
> shut up!!!!!!!



> evviva haveloc

è lui che ci rende liberi amèn semicit.

**Comment by Byrykhynho** [comment]
> è lui che ci rende liberi amèn semicit.

lo scientifico fa male

**Comment by lunamale** [comment]
> > lo scientifico fa male

no damiano fa male

**Comment by Gegerva01** [comment]
> > > lo scientifico fa male
> 
> no damiano fa male

Kissy fa male!

**Comment by Damimanda** [comment]
Ma smettetela lol

**Comment by Byrykhynho** [comment]
poareto

**Comment by sdoro** [comment]
Chiuso
