### ISSUE TITLE
Assente

### ISSUE THREAD

**Issue by Febbronia** [sdoro/4E#2]
Febbronia - 4E_18-3.0

**Comment by ImNotGiaco** [comment]
bello

**Comment by Damimanda** [comment]
Ciao Febbronia!

**Comment by Febbronia** [comment]
Buonasera, Luca è in bagno? Non lo trovo più @sonogrosso

**Comment by ImNotGiaco** [comment]
bella

**Comment by Byrykhynho** [comment]
> Buonasera, Luca è in bagno? Non lo trovo più @sonogrosso

è in palestra a fare il finto xD

**Comment by ImNotGiaco** [comment]
ti tu si sciupat

**Comment by sdoro** [comment]
fatto
